# Generated by Django 5.0.1 on 2024-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num_bureau',
            field=models.IntegerField(default=0),
        ),
    ]
