# Generated by Django 5.0.1 on 2024-02-17 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_delete_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Localisation',
        ),
        migrations.RenameField(
            model_name='localisation',
            old_name='num_bureau',
            new_name='numero_de_bureau',
        ),
    ]
