# Generated by Django 5.0.1 on 2024-02-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('users', '0010_rename_employee_localisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.localisation'),
        ),
    ]
