# Generated by Django 5.0.1 on 2024-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_hardware_software_delete_adaptateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
    ]
