# Generated by Django 5.0.1 on 2024-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=10),
            preserve_default=False,
        ),
    ]
