# Generated by Django 5.0.1 on 2024-02-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_material_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AddField(
            model_name='material',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.software'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], max_length=4),
        ),
    ]
