# Generated by Django 5.0.1 on 2024-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_material_options_material_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='material_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=10),
        ),
        migrations.AddField(
            model_name='software',
            name='material_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=10),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
