# Generated by Django 5.0.1 on 2024-02-29 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Material_fournisseur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('longueur', models.CharField(max_length=100)),
                ('type_entree', models.CharField(max_length=100)),
                ('type_sortie', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('nombre_coeurs', models.IntegerField()),
                ('frequence', models.CharField(max_length=100)),
                ('interface', models.CharField(max_length=100)),
                ('type_disque', models.CharField(max_length=100)),
                ('standard_wifi', models.CharField(max_length=100)),
                ('nombre_antennes', models.IntegerField()),
                ('carte_graphique', models.CharField(max_length=100)),
                ('processeur', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=100)),
                ('ports_disponibles', models.CharField(max_length=100)),
                ('type_panneau', models.CharField(max_length=100)),
                ('connectivite', models.CharField(max_length=100)),
                ('type_connexion', models.CharField(max_length=100)),
                ('technologie', models.CharField(max_length=100)),
                ('configuration_audio', models.CharField(max_length=100)),
                ('puissance_sortie', models.CharField(max_length=100)),
                ('autonomie_batterie', models.CharField(max_length=100)),
                ('compatibilite', models.CharField(max_length=100)),
                ('nombre_micros', models.IntegerField()),
                ('taille_ecran', models.CharField(max_length=100)),
                ('systeme_exploitation', models.CharField(max_length=100)),
                ('capacite_stockage', models.CharField(max_length=100)),
                ('memoire_ram', models.CharField(max_length=100)),
                ('capacite_salles', models.CharField(max_length=100)),
                ('fonctionnalites', models.TextField()),
                ('vision_nuit', models.BooleanField(default=False)),
                ('angle_vue', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('type_capteur', models.CharField(max_length=100)),
                ('resolution_optique', models.CharField(max_length=100)),
                ('vitesse_scan', models.CharField(max_length=100)),
                ('vitesse_impression', models.CharField(max_length=100)),
                ('resolution_impression', models.CharField(max_length=100)),
                ('capacite', models.CharField(max_length=100)),
                ('vitesse', models.CharField(max_length=100)),
                ('type_surveillance', models.CharField(max_length=100)),
                ('puissance', models.CharField(max_length=100)),
                ('autonomie', models.CharField(max_length=100)),
                ('luminosite', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateField()),
                ('duree_garantie', models.IntegerField()),
                ('duree_vie_debut', models.DateField()),
                ('duree_vie_fin', models.DateField()),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_panne', 'En panne'), ('en_reparation', 'En réparation')], max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material_fournisseur.fournisseur')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adaptateur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Material_hard.materialhard',),
        ),
        migrations.CreateModel(
            name='CableEthernet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Material_hard.materialhard',),
        ),
        migrations.CreateModel(
            name='CableUSB',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Material_hard.materialhard',),
        ),
        migrations.CreateModel(
            name='Connecteur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Material_hard.materialhard',),
        ),
    ]
