# Generated by Django 5.0.1 on 2024-02-29 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_fournisseur', '0001_initial'),
        ('Material_hard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CableUSB',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateField()),
                ('duree_garantie', models.IntegerField()),
                ('duree_vie_debut', models.DateField()),
                ('duree_vie_fin', models.DateField()),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_panne', 'En panne'), ('en_reparation', 'En réparation')], max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material_fournisseur.fournisseur')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='materialhard',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='materialhard',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Adaptateur',
        ),
        migrations.DeleteModel(
            name='CableEthernet',
        ),
        migrations.DeleteModel(
            name='Connecteur',
        ),
        migrations.CreateModel(
            name='CableUSB',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Material_hard.material')),
                ('type_entree', models.CharField(max_length=100)),
                ('type_sortie', models.CharField(max_length=100)),
                ('longueur', models.CharField(max_length=100)),
            ],
            bases=('Material_hard.material',),
        ),
        migrations.CreateModel(
            name='ServeurPC',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Material_hard.material')),
                ('processeur', models.CharField(max_length=100)),
                ('memoire_ram', models.CharField(max_length=100)),
                ('capacite_stockage', models.CharField(max_length=100)),
                ('systeme_exploitation', models.CharField(max_length=100)),
            ],
            bases=('Material_hard.material',),
        ),
        migrations.CreateModel(
            name='Souris',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Material_hard.material')),
                ('type', models.CharField(max_length=100)),
            ],
            bases=('Material_hard.material',),
        ),
        migrations.DeleteModel(
            name='MaterialHard',
        ),
    ]
