# Generated by Django 5.0.1 on 2024-02-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_hard', '0003_alter_material_table_delete_souris'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
    ]
