# Generated by Django 5.0.1 on 2024-02-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_hard', '0004_alter_material_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='material',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='serveurpc',
            name='material_ptr',
        ),
        migrations.DeleteModel(
            name='CableUSB',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ServeurPC',
        ),
    ]
