# Generated by Django 5.0.2 on 2024-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticket_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_categorie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
